# Generated by Django 3.2.5 on 2021-07-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=144)),
                ('overview', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=144)),
                ('vote_average', models.CharField(max_length=10)),
                ('vote_count', models.CharField(max_length=10)),
            ],
        ),
    ]
